### ISSUE TITLE
When logged in remove "Jagex rights" label.

### ISSUE THREAD

**Issue by patriqdesigns** [HikariKnight/rsu-client#50]
In Runescape Windows client, You have that "Runescape belongs to Jagex" box in the bottom, but when you log in it disappears. Using RSU in Linux it doesnt which results in a waste of precious space.
@HikariKnight, please remove that label once we are logged in! Or make a Add-On to remove that label, other that the fullscreen emulator (since it doesnt work in gnome).

By the way I am using Fedora 21.

PS: I am developing a Java Runescape client, and I really like your custom cache "cleaner", its really usefull for Linux. Any tips to make one like yours in Java? How do you do it, how do you make it write in a custom directory? And load from it?

Thank you very much,
PatriqDesigns

**Comment by hostonnet** [comment]
You can't remove it. What you see is not created by rsu-client, it is just jar file created by runescape.

I wanted to remove that.. so tried to "git grep", but no success, later found rsu-client have no GUI, it just call jar file provided by runescape. I don't know why Jagex add such copyright to Linux client and not on Windows client.

**Comment by PatriqDesigns** [comment]
What about the jagex cache part?
You think if I provide my own jar it would work fine?

**Comment by ivanpu** [comment]
Both the top bar and the bottom bar disappear for me, when I log in.

> What about the jagex cache part?

Clearing it will reset all client settings, and will force it to redownload the whole cache again. I have no idea if this will help in current situation.

> You think if I provide my own jar it would work fine?

This jar file is the actual game client, and it's contents are under copyright and responsibility of Jagex. Modifying it strictly against the terms of services that you agreed to when you created Jagex account.

What may help, is using one of the other 2 jars that you can get. There are 3 source options at total:
* Windows client (msi file)
* Mac client (dmg file)
* standalone jar: `http://www.runescape.com/downloads/jagexappletviewer.jar`
All those options are available from the updater, and I'm using the standalone jar.

**Comment by PatriqDesigns** [comment]
I downloaded the standalone jar and still no luck.
What I meant for clearing jagex cache, I was asking how would I be able to change the cache directory like rsu does, so I could implement it in my Runescape loader. I really wanna know how too! :+1:

**Comment by HikariKnight** [comment]
@PatriqDesigns @ivanpu @hostonnet hey
i am guessing Patriq is using Java8 which broke the language/copyright bars


tell rsu to use java7 and you should be sorted. luckily you can just extract java7 and point rsu to it through the launcher options, kinda the reason it's there as i predicted oracle would mess up more more stuff with java after the libjawt incident ;)


also changing the cache is easy (but not officially supported by jagex so they have taken measures to prevent the argument from working on the official windows client, but not the windows jar itself)


just add <pre>-user.home="path/to/cache/root"</pre> as a new argument.


keep in mind that java will use that path as the users home directory so if your loader is java based you will need to keep that in mind, also runescape will treat the client launch as a first time launch when you launch it the first time after the change.


hope this helped you and good luck with your loader :+1:

**Comment by PatriqDesigns** [comment]
You can close! Thank you alot! Please if you need any help enchancing this loader I would love to help!
Tell me something on skype: amendes_rey

**Comment by jacobmischka** [comment]
I know this is closed, but mine still seems to stay up after changing the launcher to use java7. any suggestions? @HikariKnight

**Comment by HikariKnight** [comment]
show me the terminal output, also try and refetch the jar file (preferrably the one that is nor windows/mac based as jagex have a tendency to bump spesific jar versions depending on what they fix)

**Comment by jacobmischka** [comment]
Oh wait, you know what, I'm an idiot. I've been talking about osrs, not rs3. Does that copyright bar never go away in osrs?

**Comment by HikariKnight** [comment]
I dont really play oldschool but i don't think it does, will test it today

**Comment by jeffhoe** [comment]
Did you get a chance to look at a way to remove that text at the bottom? I went looking through config files and such, couldn't really find anything. The only thing that shocks me is that in OSBuddy, it's not there. Why can they get rid of the copyright text??

**Comment by HikariKnight** [comment]
OSbuddy is using their own appletviewer while I am using the official one (hence why this client is considered a community developed official client)
Also no I did not get time to check it. If they do not disappear for me then there is a config thing on jagex end since it works on Windows.

**Comment by HikariKnight** [comment]
just checked, it is removed without issues for me with openjdk7
![old school runescape_001](https://cloud.githubusercontent.com/assets/2557889/10104308/67063604-63a9-11e5-9c2b-ff73c9bec84f.png)

**Comment by jeffhoe** [comment]
That's interesting.. I'm also running openjdk7. 

![screenshot_2015-09-25_11-33-52](https://cloud.githubusercontent.com/assets/6145757/10104770/65728f3e-6379-11e5-89a5-ec71583d9c92.png)

![screenshot_2015-09-25_11-32-54](https://cloud.githubusercontent.com/assets/6145757/10104725/4b0ce4fa-6379-11e5-948d-90d1e3fcc7bc.png)

**Comment by jacobmischka** [comment]
I'm not home right now to give info, but a friend of mine and myself are both also on arch x64 using openjdk7 and it doesn't go away.

**Comment by HikariKnight** [comment]
Could it be linked to resizable mode? I haven't played since before resizable got released (as you can see I am still dressed for last Halloween)

Farfetched theory but we can try everything before I try to poke Philip to see if he has any ideas :)

**Comment by jacobmischka** [comment]
Well. It is possible to make it look as if it's disappeared in fixed mode, though it's actually still there, just outside the window border since the UI doesn't resize when the window does. Maybe that's how it works, and why it doesn't work in resizable mode. 
![screenshot from 2015-09-26 10-42-05](https://cloud.githubusercontent.com/assets/3939997/10118350/641907f4-643b-11e5-856d-ac32c39e4579.png)

![screenshot from 2015-09-26 10-43-39](https://cloud.githubusercontent.com/assets/3939997/10118355/790af28a-643b-11e5-9b85-3d57c7a62f10.png)

**Comment by HikariKnight** [comment]
Poked Philip on twitter, will email him should that be necessary (he will most likely not respond directly on this issue ticket as jagex is not associated with the project)

**Comment by HikariKnight** [comment]
hey @jacobmischka, Philip have replied to me, here is what he said
<pre>Hi,

This was a bug that I fixed in the client fairly recently, so I suggest they update the jagexappletviewer.jar, and it might disappear! :)

Hope that helps,

Philip
Technical Director (RuneScape)
Jagex Games Studio</pre>

**Comment by allie** [comment]
Hi,
I updated the jagexappletviewer.jar file (both through the updater in your application and by downloading directly from the site), but it still does not seem to have worked unfortunately:

![screenshot from 2015-09-29 14-19-56](https://cloud.githubusercontent.com/assets/10043207/10174016/7e48c066-66b5-11e5-9713-a4a5701ddfa0.png)
![screenshot from 2015-09-29 14-19-48](https://cloud.githubusercontent.com/assets/10043207/10174021/84d00a16-66b5-11e5-8362-f8de988c6e31.png)

I know there's probably not much you can do at this point, but I thought I'd let just post to let you know I didn't have much success with the new applet viewer.
Thanks!

**Comment by HikariKnight** [comment]
ok just to rule out the possibility of you having downloaded a cached jar file (cached by your ISP, meaning it might be outdated for a few weeks), can you try this one which is the newest one
https://copy.com/FLPYQnFFNIthEunr/temp/jagexappletviewer.jar?download=1

I will keep the jar file there only for a couple of days (if you confirm it is working)
If you report it not working then i will inform philip to take another look.

PS: incase you do not know which folder to put the appletviewer in, it is $clientdir/bin

**Comment by hostonnet** [comment]
wget runescape.com/downloads/jagexappletviewer.jar?somerandom_str -O jagexappletviewer.jar

fixed it for me.

**Comment by HikariKnight** [comment]
@hostonnet ye but if its ISP cached (which have been the case with client files from jagex before) it will not bypass it with wget :/ but we will see :)
try both wget and the file i uploaded, if wget dont fetch the newest jar then use the one i uploaded which i know is the newest one.

**Comment by hostonnet** [comment]
wget won't bypass cache.

But when you have  "?" at the end of url, and some random string/number, it will be treated as different uri and will bypass the cache.

**Comment by jacobmischka** [comment]
Still no luck. Tried both the one you uploaded, and wgetting with the fake get variable. 

![screenshot from 2015-09-30 07-16-14](https://cloud.githubusercontent.com/assets/3939997/10192611/31d39038-6743-11e5-9390-852669c597c1.png)
![screenshot from 2015-09-30 07-16-24](https://cloud.githubusercontent.com/assets/3939997/10192612/3429f818-6743-11e5-9df1-bfa01666c592.png)

**Comment by HikariKnight** [comment]
Reply from Philip

> Not sure why that would be the case.  Could be something to do with the version/variety of Java they are using.

**Comment by jacobmischka** [comment]
Yeah I'm not sure, it's the most recent version of OpenJDK 7 available in the arch repositories. It does it with 8 as well. I guess I can try with oracle's java, but yours seems to work with openjdk so I don't really understand what the problem is. 
```
$ java -version
java version "1.7.0_85"
OpenJDK Runtime Environment (IcedTea 2.6.1) (Arch Linux build 7.u85_2.6.1-1-x86_64)
OpenJDK 64-Bit Server VM (build 24.85-b03, mixed mode)
```

What version do you have that it's working on, @HikariKnight?

**Comment by HostOnNet** [comment]
I am on RS 3, it is gone for me.

```
boby@fwhlin:~ $ java -version
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
boby@fwhlin:~ $ 
```

**Comment by jacobmischka** [comment]
I've never had a problem with it going away on RS3.

**Comment by HikariKnight** [comment]
Will check my Java version when I get home, currently waiting for takeaway so eta 30min to 1 hour

**Comment by jacobmischka** [comment]
Okay great, thank you.

**Comment by HikariKnight** [comment]
<pre>java version "1.7.0_75"
OpenJDK Runtime Environment (IcedTea 2.5.4) (7u75-2.5.4-1~utopic1)
OpenJDK 64-Bit Server VM (build 24.75-b04, mixed mode)
</pre>

**Comment by jacobmischka** [comment]
Still no luck after downgrading to 1.7.0_75.

**Comment by HikariKnight** [comment]
Ok this is very weird. I have no more ideas
